src/Entity/Archives.php
<?php

namespace App\Entity;

use App\Repository\ArchivesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArchivesRepository::class)
 */
class Archives
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $urlYoutube;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $urlDownload;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $urlGit;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $utilisation;

    /**
     * @ORM\Column(type="text")
     */
    private $installation;

    /**
     * @ORM\Column(type="text")
     */
    private $website_description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getUrlYoutube(): ?string
    {
        return $this->urlYoutube;
    }

    public function setUrlYoutube(string $urlYoutube): self
    {
        $this->urlYoutube = $urlYoutube;

        return $this;
    }

    public function getUrlDownload(): ?string
    {
        return $this->urlDownload;
    }

    public function setUrlDownload(string $urlDownload): self
    {
        $this->urlDownload = $urlDownload;

        return $this;
    }

    public function getUrlGit(): ?string
    {
        return $this->urlGit;
    }

    public function setUrlGit(string $urlGit): self
    {
        $this->urlGit = $urlGit;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUtilisation(): ?string
    {
        return $this->utilisation;
    }

    public function setUtilisation(string $utilisation): self
    {
        $this->utilisation = $utilisation;

        return $this;
    }

    public function getInstallation(): ?string
    {
        return $this->installation;
    }

    public function setInstallation(string $installation): self
    {
        $this->installation = $installation;

        return $this;
    }

    public function getWebsiteDescription(): ?string
    {
        return $this->website_description;
    }

    public function setWebsiteDescription(string $website_description): self
    {
        $this->website_description = $website_description;

        return $this;
    }
}

src/Form/ArchivesType.php
<?php

namespace App\Form;

use App\Entity\Archives;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArchivesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Type')
            ->add('urlYoutube')
            ->add('urlDownload')
            ->add('urlGit')
            ->add('title')
            ->add('content')
            ->add('description')
            ->add('utilisation')
            ->add('installation')
            ->add('website_description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Archives::class,
        ]);
    }
}

src/Controller/ArchivesController.php
<?php

namespace App\Controller;

use App\Form\SearchType;
use App\Entity\Archives;
use App\Form\ArchivesType;
use App\Repository\ArchivesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/archives")
 */
class ArchivesController extends AbstractController
{
    /**
     * @Route("/", name="archives_index", methods={"GET"})
     */
    public function index(ArchivesRepository $archivesRepository): Response
    {
        return $this->render('archives/index.html.twig', [
            'archives' => $archivesRepository->findAll(),
            'pageTitle' => 'Archives', 
        ]);
    }

    /**
     * @Route("/packages", name="packages", methods={"GET"})
     */
    public function showPackages(ArchivesRepository $archivesRepository): Response
    {
        $searchForm = $this->createForm(SearchType::class);
        return $this->render('archives/packages/show.html.twig', [
            'packages' => $archivesRepository->findPackages(),
            'pageTitle' => 'Packages', 
            'search_form' => $searchForm->createView(),
        ]);
    }

       /**
     * @Route("/designpatterns", name="design_patterns", methods={"GET"})
     */
    public function showDesignPatterns(ArchivesRepository $archivesRepository): Response
    {
        return $this->render('archives/design_patterns/show.html.twig', [
            'designs' => $archivesRepository->findDesingPatterns(),
            'pageTitle' => 'Design Patterns', 
        ]);
    }

       /**
     * @Route("/modules", name="modules", methods={"GET"})
     */
    public function showModules(ArchivesRepository $archivesRepository): Response
    {
        return $this->render('archives/modules/show.html.twig', [
            'modules' => $archivesRepository->findModules(),
            'pageTitle' => 'Modules', 
        ]);
    }

       /**
     * @Route("/extensions", name="extensions", methods={"GET"})
     */
    public function showExtensions(ArchivesRepository $archivesRepository): Response
    {
        return $this->render('archives/extensions/show.html.twig', [
            'extensions' => $archivesRepository->findExtensions(),
            'pageTitle' => 'Extensions', 
        ]);
    }

       /**
     * @Route("/library", name="library", methods={"GET"})
     */
    public function showLibrary(ArchivesRepository $archivesRepository): Response
    {
        return $this->render('archives/library/show.html.twig', [
            'libraries' => $archivesRepository->findLibrary(),
            'pageTitle' => 'Library', 
        ]);
    }

       /**
     * @Route("/services", name="services", methods={"GET"})
     */
    public function showServices(ArchivesRepository $archivesRepository): Response
    {
        return $this->render('archives/services/show.html.twig', [
            'services' => $archivesRepository->findServices(),
            'pageTitle' => 'Services', 
        ]);
    }

    /**
     * @Route("/new", name="archives_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $archive = new Archives();
        $form = $this->createForm(ArchivesType::class, $archive);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($archive);
            $entityManager->flush();

            return $this->redirectToRoute('archives_index');
        }

        return $this->render('archives/new.html.twig', [
            'archive' => $archive,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="archives_show", methods={"GET"})
     */
    public function show(Archives $archive): Response
    {
        return $this->render('archives/show.html.twig', [
            'archive' => $archive,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="archives_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Archives $archive): Response
    {
        $form = $this->createForm(ArchivesType::class, $archive);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('archives_index');
        }

        return $this->render('archives/edit.html.twig', [
            'archive' => $archive,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="archives_delete", methods={"POST"})
     */
    public function delete(Request $request, Archives $archive): Response
    {
        if ($this->isCsrfTokenValid('delete'.$archive->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($archive);
            $entityManager->flush();
        }

        return $this->redirectToRoute('archives_index');
    }
}

templates/archives/_delete_form.html.twig
<form method="post" action="{{ path('archives_delete', {'id': archive.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ archive.id) }}">
    <button class="btn">Delete</button>
</form>

templates/archives/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/archives/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Archives{% endblock %}

{% block body %}
    <h1>Edit Archives</h1>

    {{ include('archives/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('archives_index') }}">back to list</a>

    {{ include('archives/_delete_form.html.twig') }}
{% endblock %}

templates/archives/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ pageTitle }}{% endblock %}

{% block body %}
    <h1>Archives index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Type</th>
                <th>UrlYoutube</th>
                <th>UrlDownload</th>
                <th>UrlGit</th>
                <th>Title</th>
                <th>Content</th>
                <th>Description</th>
                <th>Utilisation</th>
                <th>Installation</th>
                <th>Website_description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for archive in archives %}
            <tr>
                <td>{{ archive.id }}</td>
                <td>{{ archive.Type }}</td>
                <td>{{ archive.urlYoutube }}</td>
                <td>{{ archive.urlDownload }}</td>
                <td>{{ archive.urlGit }}</td>
                <td>{{ archive.title }}</td>
                <td>{{ archive.content }}</td>
                <td>{{ archive.description }}</td>
                <td>{{ archive.utilisation }}</td>
                <td>{{ archive.installation }}</td>
                <td>{{ archive.websiteDescription }}</td>
                <td>
                    <a href="{{ path('archives_show', {'id': archive.id}) }}">show</a>
                    <a href="{{ path('archives_edit', {'id': archive.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('archives_new') }}">Create new</a>
{% endblock %}

templates/archives/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Archives{% endblock %}

{% block body %}
    <h1>Create new Archives</h1>

    {{ include('archives/_form.html.twig') }}

    <a href="{{ path('archives_index') }}">back to list</a>
{% endblock %}

templates/archives/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Archives{% endblock %}

{% block body %}
    <h1>Archives</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ archive.id }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ archive.Type }}</td>
            </tr>
            <tr>
                <th>UrlYoutube</th>
                <td>{{ archive.urlYoutube }}</td>
            </tr>
            <tr>
                <th>UrlDownload</th>
                <td>{{ archive.urlDownload }}</td>
            </tr>
            <tr>
                <th>UrlGit</th>
                <td>{{ archive.urlGit }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ archive.title }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ archive.content }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ archive.description }}</td>
            </tr>
            <tr>
                <th>Utilisation</th>
                <td>{{ archive.utilisation }}</td>
            </tr>
            <tr>
                <th>Installation</th>
                <td>{{ archive.installation }}</td>
            </tr>
            <tr>
                <th>Website_description</th>
                <td>{{ archive.websiteDescription }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('archives_index') }}">back to list</a>

    <a href="{{ path('archives_edit', {'id': archive.id}) }}">edit</a>

    {{ include('archives/_delete_form.html.twig') }}
{% endblock %}